- id: '1620071993063'
  alias: Disarm Blink (Improved)
  description: Disarms the Blink alarm system at 7:00 AM.
  triggers:
  - at: 07:00:00
    trigger: time
  actions:
  - target:
      entity_id: alarm_control_panel.blink_house
    action: alarm_control_panel.alarm_disarm
  mode: single
- id: '1672867600743'
  alias: Midnight Gas and Electric Notifications
  description: Sends daily gas and electric cost notifications at midnight
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: notify.telegram_bot
    data:
      message: 'Good morning! Here are today''s energy costs:

        Today''s gas cost is {{ states(''sensor.smart_meter_gas_cost_today'') }}.

        Today''s electric cost is {{ states(''sensor.smart_meter_electricity_cost_today'')
        }}

        '
  - service: notify.email
    data:
      message: 'Good morning! Here are today''s energy costs:

        Today''s gas cost is {{ states(''sensor.smart_meter_gas_cost_today'') }}.

        Today''s electric cost is {{ states(''sensor.smart_meter_electricity_cost_today'')
        }}

        '
  mode: single
- id: '1686042092819'
  alias: If DNS is turned off for longer than an hour, turn on
  description: ''
  triggers:
  - type: turned_off
    device_id: b752bdeb86ff9b2e9476be2a2ece9357
    entity_id: 3ab15b259b2971ed4774eaaddd987cb9
    domain: switch
    trigger: device
  conditions:
  - condition: or
    conditions:
    - type: is_running
      condition: device
      device_id: 72d9feb7375173d69f415053f71847d8
      entity_id: 0f6bb2e86af34b37f9c35a4109020c94
      domain: binary_sensor
  actions:
  - delay: 01:00:00
  - target:
      entity_id: switch.adguard_protection
    data: {}
    action: switch.turn_on
  - data:
      message: DNS turned off!
    action: notify.telegram_bot
  mode: single
- id: '1686317391934'
  alias: Low Battery
  description: ''
  use_blueprint:
    path: gmlupatelli/low_battery_notification.yaml
    input:
      actions:
      - service: notify.telegram_bot
        data:
          message: '"low battery: {{ sensors}}"'
  mode: single
- id: '1688339061635'
  alias: 'Garden Light on for more than 10 minutes '
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: b11e5a8be43e648563eafe34653066d7
    entity_id: switch.socket_7_socket
    domain: switch
    for:
      hours: 0
      minutes: 20
      seconds: 0
  - platform: device
    type: turned_on
    device_id: 4c16aa2e8ab360f59cef97034e418217
    entity_id: 49124585207f7e62d8b71fcc7f6947f2
    domain: light
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: b11e5a8be43e648563eafe34653066d7
    entity_id: switch.socket_7_socket
    domain: switch
  mode: single
- id: '1688768949634'
  alias: 'Conservatory light on if movement '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.conservatory_camera_cell_motion_detection
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: 4c16aa2e8ab360f59cef97034e418217
    entity_id: 49124585207f7e62d8b71fcc7f6947f2
    domain: light
  - type: turn_on
    device_id: b11e5a8be43e648563eafe34653066d7
    entity_id: c845cf7e7261566197341334093fba75
    domain: switch
  - delay:
      hours: 0
      minutes: 4
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 4c16aa2e8ab360f59cef97034e418217
    entity_id: 49124585207f7e62d8b71fcc7f6947f2
    domain: light
  - type: turn_off
    device_id: b11e5a8be43e648563eafe34653066d7
    entity_id: c845cf7e7261566197341334093fba75
    domain: switch
  - target:
      entity_id: input_number.automation_run_count
    data: {}
    action: input_number.increment
  - data_template:
      entity_id: input_number.light_on_minutes
      value: '{{ (states(''input_number.light_on_minutes'') | int) + 3 }}'
    action: input_number.set_value
  mode: single
- id: '1689329658622'
  alias: Back Door Open
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.door_sensor
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      message: The back door is open.
      title: Your back door Friend
      target:
      - media_player.master_bedroom_echo
      - media_player.downstairs_echo
      - media_player.paul_s_2nd_alexa_app_for_pc
      data:
        type: tts
  mode: single
- id: '1689333385634'
  alias: Evening Gas and Electric Notifications
  description: Sends daily gas and electric cost notifications in the evening
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - service: notify.telegram_bot
    data:
      message: 'Good evening! Here are today''s energy costs:

        Today''s gas cost is {{ states(''sensor.smart_meter_gas_cost_today_2'') }}.

        Today''s electric cost is {{ states(''sensor.smart_meter_electricity_cost_today_2'')
        }}

        '
  - service: notify.email
    data:
      message: 'Good evening! Here are today''s energy costs:

        Today''s gas cost is {{ states(''sensor.smart_meter_gas_cost_today_2'') }}.

        Today''s electric cost is {{ states(''sensor.smart_meter_electricity_cost_today_2'')
        }}

        '
  mode: single
- id: '1689342086245'
  alias: Push updates to GitHub
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.upload_config_to_github
    data: {}
  - service: persistent_notification.create
    data:
      message: 'GitHub update attempt: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
      title: GitHub Update
  - service: system_log.write
    data:
      level: error
      message: 'GitHub update attempt: {{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
  mode: single
- id: '1690464825109'
  alias: Watchman
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition: []
  action:
  - service: watchman.report
    data:
      create_file: true
      send_notification: true
      parse_config: false
      chunk_size: false
      service: notify.group_telegram_and_email
  mode: single
- id: '1691748663178'
  alias: Home Assistant Auto-update on a schedule base
  description: ''
  use_blueprint:
    path: edwardtfn/auto_update_scheduled.yaml
    input:
      schedule_entity: schedule.update_schedule
      verbose_logging_bool: true
- id: '1694685095232'
  alias: Repack DB Every Sunday
  description: Repack DB Every Sunday
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: recorder.purge
    data:
      repack: true
  mode: single
- id: '1709392756507'
  alias: Light strip
  description: ''
  trigger:
  - platform: sun
    event: sunset
  - platform: time
    at: '23:00:00'
  condition:
  - condition: time
    before: '23:00:00'
    after: '17:00:00'
  action:
  - choose:
    - conditions:
      - condition: time
        before: '23:00:00'
      sequence:
      - type: turn_on
        device_id: cb8a4a776f0b561b4c61a8d186e67a02
        entity_id: 8f30db09dcccdefeff629a6b75dc149d
        domain: light
    - conditions:
      - condition: time
        after: '23:00:00'
      sequence:
      - type: turn_off
        device_id: cb8a4a776f0b561b4c61a8d186e67a02
        entity_id: 8f30db09dcccdefeff629a6b75dc149d
        domain: light
  mode: single
- id: '1734441709415'
  alias: Alert if Telegram Bot Goes Offline
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.telegram_bot_health
    to:
    trigger: state
    from: 'on'
  conditions: []
  actions:
  - data:
      message: ⚠️ The Telegram Forwarder Bot has gone offline!
    action: notify.telegram_bot
  - action: notify.mobile_app_moto_g55_5g
    metadata: {}
    data:
      message: Bot OFFLINE
      title: Bot OFFLINE
  mode: single
- id: '1734441792315'
  alias: System Resource Alert
  description: Sends a Telegram notification when CPU, Memory, or Swap usage exceeds
    a threshold.
  triggers:
  - entity_id: sensor.glances_cpu_used
    above: 80
    id: cpu_high
    trigger: numeric_state
  - entity_id: sensor.glances_ram_used_percent
    above: 85
    id: memory_high
    trigger: numeric_state
  - entity_id: sensor.glances_swap_used_percent
    above: 75
    id: swap_high
    trigger: numeric_state
  - entity_id: sensor.dietpi_metrics_dietpi_cpu_usage
    above: 90
    id: dietpi_cpu_high
    trigger: numeric_state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: cpu_high
      sequence:
      - data:
          message: ⚠️ High CPU Usage Alert! CPU usage is above 80% on HASSIO(Glances
            sensor).
        action: notify.telegram_bot
    - conditions:
      - condition: trigger
        id: memory_high
      sequence:
      - data:
          message: ⚠️ High Memory Usage Alert! Memory usage is above 85% on HASSIO
        action: notify.telegram_bot
    - conditions:
      - condition: trigger
        id: swap_high
      sequence:
      - data:
          message: ⚠️ High Swap Usage Alert! Swap usage is above 75% on HASSIO
        action: notify.telegram_bot
    - conditions:
      - condition: trigger
        id: dietpi_cpu_high
      sequence:
      - data:
          message: '⚠️ Warning: CPU Usage on DietPi has exceeded 90%!'
        action: notify.telegram_bot
- id: '1740662831776'
  alias: 'Alert: Orange Pi Offline'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.192_168_3_20
    from: 'on'
    to:
  conditions: []
  actions:
  - action: notify.telegram_bot
    metadata: {}
    data:
      title: ⚠️ Orange Pi Offline
      message: The Orange Pi (192.168.3.20) has been unreachable for 5+ minutes!
  - action: notify.mobile_app_moto_g55_5g
    metadata: {}
    data:
      message: The Orange Pi (192.168.3.20) has been unreachable for 5+ minutes!
      title: ⚠️ Orange Pi Offline
  mode: single
- id: '1740672510375'
  alias: Polling for ICMP
  description: ''
  triggers:
  - trigger: time_pattern
    hours: '*'
    minutes: '*'
    seconds: '1'
  conditions: []
  actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
      - sensor.192_168_3_20_round_trip_time_average
      - sensor.192_168_3_20_round_trip_time_maximum
      - sensor.192_168_3_20_round_trip_time_minimum
      - binary_sensor.192_168_3_20
      - binary_sensor.telegram_bot_health
  mode: single
- id: '1745328602055'
  alias: Arm Blink at Night (Even When Home)
  description: Arms the Blink alarm system in away mode at 10:00 PM.
  triggers:
  - at: '22:00:00'
    trigger: time
  conditions:
  - condition: time
    after: '22:00:00'
    before: 06:00:00
  actions:
  - target:
      entity_id: alarm_control_panel.blink_house
    action: alarm_control_panel.alarm_arm_away
  mode: single
